backend:
  name: github
  repo: your-username/your-repo
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
